name: "Mark Saroufim"
description: ""

url: "http://localhost:4000"

paginate: 10
permalink: pretty

comments :
  provider : disqus
  disqus :
    short_name : jekyllbootstrap
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light