name: "Mark Saroufim"
description: "My blog about machine learning, technology and philosophy"

url: "127.0.0.1:4000"

paginate: 10
permalink: pretty
highlighter: pygments
pages_list:       
  About: '/about'
  Archive: '/archive'
  #LinkedIn/CV
  #Github

comments : true
  # provider : disqus
  # disqus :
  #   short_name : marksaroufim
  # livefyre :
  #   site_id : 123
  # intensedebate :
  #   account : 123abc
  # facebook :
  #   appid : 123
  #   num_posts: 5
  #   width: 580
  #   colorscheme: light

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
